export const LOGIN = 'LOGIN'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILED = 'LOGIN_FAILED'

export const LOGOUT = 'LOGOUT'

// Book actions
export const GET_TOP_VIEW_BOOK = 'GET_TOP_VIEW_BOOK'
export const GET_TOP_VIEW_BOOK_SUCCESS = 'GET_TOP_VIEW_BOOK_SUCCESS'
export const GET_HOT_BOOKS = 'GET_HOT_BOOKS'
export const GET_HOT_BOOKS_SUCCESS = 'GET_HOT_BOOKS_SUCCESS'

// Subject actions
export const GET_LIST_SUBJECTS = 'GET_LIST_SUBJECTS'
export const GET_LIST_SUBJECTS_SUCCESS = 'GET_LIST_SUBJECTS_SUCCESS'
export const GET_BOOKS_BY_SUBJECT = 'GET_BOOKS_BY_SUBJECT'
export const GET_BOOKS_BY_SUBJECT_SUCCESS = 'GET_BOOKS_BY_SUBJECT_SUCCESS'

// Book Details
export const GET_BOOK_DETAIL = 'GET_BOOK_DETAIL'
export const GET_BOOK_DETAIL_SUCCESS = 'GET_BOOK_DETAIL_SUCCESS'
